const mongoose = require('mongoose');

const attendanceSchema = new mongoose.Schema({
  employee: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Employee',
    required: true
  },
  date: {
    type: Date,
    required: true
  },
  checkIn: {
    time: Date,
    location: {
      latitude: Number,
      longitude: Number,
      address: String
    },
    method: {
      type: String,
      enum: ['manual', 'biometric', 'mobile', 'web', 'face-detection'],
      default: 'web'
    },
    deviceInfo: {
      userAgent: String,
      browser: String,
      os: String,
      device: String
    },
    ipAddress: String,
    screenshot: String, // Base64 or file path
    faceImage: String, // Path to face image for face detection attendance
    faceEmbedding: String, // Face embedding for verification
    isValidLocation: {
      type: Boolean,
      default: false
    },
    locationValidation: {
      ipValid: Boolean,
      geoValid: Boolean,
      wifiValid: Boolean
    }
  },
  checkOut: {
    time: Date,
    location: {
      latitude: Number,
      longitude: Number,
      address: String
    },
    method: {
      type: String,
      enum: ['manual', 'biometric', 'mobile', 'web', 'face-detection'],
      default: 'web'
    },
    deviceInfo: {
      userAgent: String,
      browser: String,
      os: String,
      device: String
    },
    ipAddress: String,
    earlyLeaveReason: String,
    faceImage: String, // Path to face image for face detection attendance
    faceEmbedding: String, // Face embedding for verification
    isValidLocation: {
      type: Boolean,
      default: false
    }
  },
  breaks: [{
    breakOut: Date,
    breakIn: Date,
    reason: String,
    duration: Number, // in minutes
    type: {
      type: String,
      enum: ['lunch', 'tea', 'personal', 'meeting', 'idle'],
      default: 'personal'
    },
    isAutoGenerated: {
      type: Boolean,
      default: false
    }
  }],
  idleTime: {
    totalIdleMinutes: {
      type: Number,
      default: 0
    },
    idleSessions: [{
      startTime: Date,
      endTime: Date,
      duration: Number, // in minutes
      reason: String,
      wasWarned: Boolean,
      autoLogout: Boolean
    }]
  },
  punchRecords: [{
    time: {
      type: Date,
      required: true
    },
    type: {
      type: String,
      enum: ['in', 'out'],
      required: true
    },
    method: {
      type: String,
      enum: ['manual', 'biometric', 'mobile', 'web', 'face-detection'],
      default: 'biometric'
    },
    deviceName: String,
    deviceSerialNumber: String,
    location: {
      latitude: Number,
      longitude: Number,
      address: String
    },
    ipAddress: String,
    notes: String
  }],
  totalHours: {
    type: Number,
    default: 0
  },
  regularHours: {
    type: Number,
    default: 0
  },
  overtimeHours: {
    type: Number,
    default: 0
  },
  status: {
    type: String,
    enum: ['present', 'absent', 'late', 'half-day', 'holiday', 'weekend', 'on-leave'],
    default: 'present'
  },
  workFromHome: {
    type: Boolean,
    default: false
  },
  leaveRequest: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'LeaveRequest'
  },
  isLate: {
    type: Boolean,
    default: false
  },
  lateMinutes: {
    type: Number,
    default: 0
  },
  earlyDeparture: {
    type: Boolean,
    default: false
  },
  earlyDepartureMinutes: {
    type: Number,
    default: 0
  },
  flexibleEndTime: {
    type: Date,
    default: null
  },
  isAutoCheckout: {
    type: Boolean,
    default: false
  },
  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Employee'
  },
  approvedAt: Date,
  notes: String,
  isManualEntry: {
    type: Boolean,
    default: false
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Calculate total hours and status before saving
attendanceSchema.pre('save', function(next) {
  // Update check-in and check-out from punch records if available
  if (this.punchRecords && this.punchRecords.length > 0) {
    // Sort punch records by time
    const sortedPunches = [...this.punchRecords].sort((a, b) => new Date(a.time) - new Date(b.time));
    
    // First punch = Check-in
    const firstPunch = sortedPunches[0];
    if (!this.checkIn?.time || new Date(firstPunch.time) < new Date(this.checkIn.time)) {
      if (!this.checkIn) this.checkIn = {};
      this.checkIn.time = firstPunch.time;
      this.checkIn.method = firstPunch.method || 'biometric';
    }
    
    // Last punch = Check-out
    const lastPunch = sortedPunches[sortedPunches.length - 1];
    if (sortedPunches.length > 1 && (!this.checkOut?.time || new Date(lastPunch.time) > new Date(this.checkOut.time))) {
      if (!this.checkOut) this.checkOut = {};
      this.checkOut.time = lastPunch.time;
      this.checkOut.method = lastPunch.method || 'biometric';
    }
  }
  
  // Calculate total hours if both check-in and check-out exist
  if (this.checkIn?.time && this.checkOut?.time) {
    const totalMs = this.checkOut.time - this.checkIn.time;
    
    // Subtract break time
    const breakTime = this.breaks.reduce((total, brk) => {
      if (brk.breakOut && brk.breakIn) {
        return total + (brk.breakIn - brk.breakOut);
      }
      return total;
    }, 0);
    
    this.totalHours = Math.max(0, (totalMs - breakTime) / (1000 * 60 * 60)); // Convert to hours
    
    // Calculate regular and overtime hours (assuming 8 hours is regular)
    this.regularHours = Math.min(this.totalHours, 8);
    this.overtimeHours = Math.max(0, this.totalHours - 8);
  }

  // Update timestamp
  this.updatedAt = Date.now();
  next();
});

// Indexes for better query performance
attendanceSchema.index({ employee: 1, date: 1 }, { unique: true });
attendanceSchema.index({ date: 1 });
attendanceSchema.index({ status: 1 });

module.exports = mongoose.model('Attendance', attendanceSchema);

